---
linters:
    enable-all: true
    disable:
      - varnamelen
      - gomoddirectives
      - nlreturn
      - wsl
      - usestdlibvars # needs to be fixed
      - exhaustruct   # needs to be fixed
      - depguard
      - tenv

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
    - linters:
        - lll
      source: "^//go:generate "
    - path: controller/version.go
      linters:
        - gochecknoglobals
    - path: _test\.go
      linters:
        - funlen
        - ireturn
    - path: image/image.go
      linters:
        - nosnakecase
