---
linters:
    enable-all: true
    disable:
      # - gochecknoglobals
      # - gochecknoinits
      # - lll
      # - gomnd
      # - gofumpt
      # - paralleltest
      # - testpackage
      # - forbidigo
      - gomoddirectives
      - nlreturn
      - wsl
      - exhaustivestruct
      - maligned  # deprecated
      - scopelint  # deprecated
      - interfacer  # deprecated
      - golint  # deprecated

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
    - text: "variable name 'ok' is too short for the scope of its usage"
      linters:
        - varnamelen
    - text: "variable name 'b' is too short for the scope of its usage"
      linters:
        - varnamelen
    - text: "parameter name 'wr' is too short for the scope of its usage"
      linters:
        - varnamelen
    - linters:
        - lll
      source: "^//go:generate "
    - path: controller/version.go
      linters:
        - gochecknoglobals
    - path: _test\.go
      linters:
        - funlen
        - ireturn
        - varnamelen
