---
name: Build containers and publish them

env:
  CONTAINER_NAME: nhost/hasura-storage

on:
  workflow_call:
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  push-docker-manifest-aws:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-nhost-${{ github.event.repository.name }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - run: |
          export VERSION=$(make get-version)
          export ECR_CONTAINER_NAME=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/hasura-storage

          docker pull $CONTAINER_NAME:$VERSION-x86_64
          docker tag $CONTAINER_NAME:$VERSION-x86_64 $ECR_CONTAINER_NAME:$VERSION-x86_64
          docker push $ECR_CONTAINER_NAME:$VERSION-x86_64
          docker pull $CONTAINER_NAME:$VERSION-aarch64
          docker tag $CONTAINER_NAME:$VERSION-aarch64 $ECR_CONTAINER_NAME:$VERSION-aarch64
          docker push $ECR_CONTAINER_NAME:$VERSION-aarch64

          docker manifest create \
              $ECR_CONTAINER_NAME:$VERSION \
              --amend $ECR_CONTAINER_NAME:$VERSION-x86_64 \
              --amend $ECR_CONTAINER_NAME:$VERSION-aarch64
          docker manifest push $ECR_CONTAINER_NAME:$VERSION
