---
name: Run tests and linters
on:
  - push
  - pull_request
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests
      run: make tests
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.43.0
